/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;

import java.awt.Color;

/**
 *
 * @author Karan Gohel
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Add_Fees = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        View_Record = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        View_Report = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        view_course = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Search_Record = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Edit_Course = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  SHREE R.P. BHALODIA COLLEGE");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 810, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("B.Com  -  B.B.A.  -  B.C.A.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("7, MANHAR PLOT,RAJKOT-2. PH.:2460012");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 390, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 210));

        jPanel2.setBackground(new java.awt.Color(0, 152, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add_Fees.setBackground(new java.awt.Color(0, 102, 102));
        Add_Fees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        Add_Fees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_FeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_FeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_FeesMouseExited(evt);
            }
        });
        Add_Fees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/plus.png"))); // NOI18N
        jLabel2.setText("  Add Fees");
        Add_Fees.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 180));

        jPanel2.add(Add_Fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 300, 210));

        View_Record.setBackground(new java.awt.Color(0, 102, 102));
        View_Record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        View_Record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_RecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                View_RecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                View_RecordMouseExited(evt);
            }
        });
        View_Record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        jLabel5.setText("  View Record");
        View_Record.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 180));

        jPanel2.add(View_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 300, 210));

        View_Report.setBackground(new java.awt.Color(0, 102, 102));
        View_Report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        View_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_ReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                View_ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                View_ReportMouseExited(evt);
            }
        });
        View_Report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view report.png"))); // NOI18N
        jLabel6.setText(" View Report");
        View_Report.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 180));

        jPanel2.add(View_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 300, 210));

        view_course.setBackground(new java.awt.Color(0, 102, 102));
        view_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        view_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_courseMouseExited(evt);
            }
        });
        view_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/text-book-opened-from-top-view.png"))); // NOI18N
        jLabel7.setText("  View Course");
        view_course.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 180));

        jPanel2.add(view_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 300, 210));

        Search_Record.setBackground(new java.awt.Color(0, 102, 102));
        Search_Record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        Search_Record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_RecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_RecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Search_RecordMouseExited(evt);
            }
        });
        Search_Record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search-document.png"))); // NOI18N
        jLabel8.setText("Search Record");
        Search_Record.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 180));

        jPanel2.add(Search_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 300, 210));

        About.setBackground(new java.awt.Color(0, 102, 102));
        About.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });
        About.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/about.png"))); // NOI18N
        jLabel1.setText("About");
        About.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 60));

        jPanel2.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 500, 180, 60));

        Edit_Course.setBackground(new java.awt.Color(0, 102, 102));
        Edit_Course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        Edit_Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit_CourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Edit_CourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Edit_CourseMouseExited(evt);
            }
        });
        Edit_Course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit.png"))); // NOI18N
        jLabel11.setText("Edit Course");
        Edit_Course.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 180));

        jPanel2.add(Edit_Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 300, 210));

        Logout.setBackground(new java.awt.Color(0, 102, 102));
        Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        jLabel3.setText("Log Out");
        Logout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 40));

        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 180, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1420, 580));

        setSize(new java.awt.Dimension(1431, 825));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_FeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_FeesMouseEntered
        Color clr=new Color(0,51,51);
        Add_Fees.setBackground(clr);
    }//GEN-LAST:event_Add_FeesMouseEntered

    private void Add_FeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_FeesMouseExited
        Color clr=new Color(0,102,102);
        Add_Fees.setBackground(clr);
    }//GEN-LAST:event_Add_FeesMouseExited

    private void View_RecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_RecordMouseEntered
        Color clr=new Color(0,51,51);
        View_Record.setBackground(clr);
    }//GEN-LAST:event_View_RecordMouseEntered

    private void View_RecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_RecordMouseExited
        Color clr=new Color(0,102,102);
        View_Record.setBackground(clr);
    }//GEN-LAST:event_View_RecordMouseExited

    private void View_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_ReportMouseEntered
        Color clr=new Color(0,51,51);
        View_Report.setBackground(clr);
    }//GEN-LAST:event_View_ReportMouseEntered

    private void View_ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_ReportMouseExited
        Color clr=new Color(0,102,102);
        View_Report.setBackground(clr);
    }//GEN-LAST:event_View_ReportMouseExited

    private void view_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_courseMouseEntered
        Color clr=new Color(0,51,51);
        view_course.setBackground(clr);
    }//GEN-LAST:event_view_courseMouseEntered

    private void view_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_courseMouseExited
        Color clr=new Color(0,102,102);
        view_course.setBackground(clr);
    }//GEN-LAST:event_view_courseMouseExited

    private void Search_RecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_RecordMouseEntered
        Color clr=new Color(0,51,51);
        Search_Record.setBackground(clr);
    }//GEN-LAST:event_Search_RecordMouseEntered

    private void Search_RecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_RecordMouseExited
        Color clr=new Color(0,102,102);
        Search_Record.setBackground(clr);
    }//GEN-LAST:event_Search_RecordMouseExited

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        Color clr=new Color(0,51,51);
        About.setBackground(clr);
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        Color clr=new Color(0,102,102);
        About.setBackground(clr);
    }//GEN-LAST:event_AboutMouseExited

    private void Edit_CourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_CourseMouseEntered
        Color clr=new Color(0,51,51);
        Edit_Course.setBackground(clr);
    }//GEN-LAST:event_Edit_CourseMouseEntered

    private void Edit_CourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_CourseMouseExited
        Color clr=new Color(0,102,102);
        Edit_Course.setBackground(clr);
    }//GEN-LAST:event_Edit_CourseMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Color clr=new Color(0,51,51);
        Logout.setBackground(clr);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        Color clr=new Color(0,102,102);
        Logout.setBackground(clr);
    }//GEN-LAST:event_LogoutMouseExited

    private void Add_FeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_FeesMouseClicked
        AddFees addfees = new AddFees();
        addfees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Add_FeesMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Login_Page logout = new Login_Page();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void View_RecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_RecordMouseClicked
        View_All_Record_Page viewRecord = new View_All_Record_Page();
        viewRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_View_RecordMouseClicked

    private void view_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_courseMouseClicked
         View_Course_Page course = new View_Course_Page();
        course.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_courseMouseClicked

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        About about = new About();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AboutMouseClicked

    private void Edit_CourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_CourseMouseClicked
        update_course_page updateCourse = new update_course_page();
        updateCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Edit_CourseMouseClicked

    private void View_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_ReportMouseClicked
        Report_Page report = new Report_Page();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_View_ReportMouseClicked

    private void Search_RecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_RecordMouseClicked
        search_record_page searchRecord = new search_record_page();
        searchRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Search_RecordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JPanel Add_Fees;
    private javax.swing.JPanel Edit_Course;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Search_Record;
    private javax.swing.JPanel View_Record;
    private javax.swing.JPanel View_Report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel view_course;
    // End of variables declaration//GEN-END:variables
}
