/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;


/**
 *
 * @author Karan Gohel
 */
public class Report_Page extends javax.swing.JFrame {

    /**
     * Creates new form Report_Page
     */
    public Report_Page() {
        initComponents();
        fillComboBox();
    }
    public void fillComboBox()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select cname from course");
            ResultSet rs =  pst.executeQuery();
            while (rs.next()) {
                combo_course.addItem(rs.getString("cname"));
            }            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_course = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_words = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_selectcourse = new javax.swing.JLabel();
        lbl_amount_collected = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_print = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewrecord = new javax.swing.JTable();
        combo_course = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combo_lastday = new javax.swing.JComboBox<>();
        panelSidebar = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        panelSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        panelEditCourse = new javax.swing.JPanel();
        btnEditCourse = new javax.swing.JLabel();
        panelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_course.setBackground(new java.awt.Color(0, 153, 153));
        txt_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Report");
        txt_course.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 110, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Amount In Words :");
        txt_course.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Course :");
        txt_course.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 160, -1));

        lbl_words.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_words.setForeground(new java.awt.Color(255, 255, 255));
        txt_course.add(lbl_words, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 500, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Amount Collected :");
        txt_course.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Course Selected :");
        txt_course.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 190, -1));

        lbl_selectcourse.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_selectcourse.setForeground(new java.awt.Color(255, 255, 255));
        txt_course.add(lbl_selectcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 220, 30));

        lbl_amount_collected.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbl_amount_collected.setForeground(new java.awt.Color(255, 255, 255));
        txt_course.add(lbl_amount_collected, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 220, 30));
        txt_course.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 570, 30));
        txt_course.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 570, 40));

        btn_print.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        txt_course.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 140, 40));

        btn_submit.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        txt_course.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, 40));

        tbl_viewrecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt No", "Roll No", "Student Name", "Course Name", "Total Amount", "Payment Mode", "Date", "Reamrks"
            }
        ));
        jScrollPane1.setViewportView(tbl_viewrecord);

        txt_course.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 1110, 510));

        combo_course.setToolTipText("Cash\nChaque\nNet Banking");
        combo_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_courseActionPerformed(evt);
            }
        });
        txt_course.add(combo_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 310, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Date : ");
        txt_course.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));

        combo_lastday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last 7 Days", "Last 1 Month", "Last 6 Month", "Last 1 Year", "Last 3 Year", "Last 6 Year" }));
        combo_lastday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_lastdayActionPerformed(evt);
            }
        });
        txt_course.add(combo_lastday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, 30));

        getContentPane().add(txt_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1650, 880));

        panelSidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(0, 102, 102));
        btnHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        lblHome.setText("  Home");
        lblHome.setToolTipText("");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        btnHome.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        panelSidebar.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 250, 70));

        panelSearchRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        panelSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSearchRecordMouseExited(evt);
            }
        });
        panelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSearchRecord.setText("Search Record");
        btnSearchRecord.setToolTipText("");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        panelSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        panelSidebar.add(panelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 250, 70));

        panelEditCourse.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        panelEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditCourseMouseExited(evt);
            }
        });
        panelEditCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourse.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEditCourse.setText("  Edit Course");
        btnEditCourse.setToolTipText("");
        btnEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseExited(evt);
            }
        });
        panelEditCourse.add(btnEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        panelSidebar.add(panelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 250, 70));

        panelCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        panelCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCourseListMouseExited(evt);
            }
        });
        panelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btnCourseList.setText("Course List");
        btnCourseList.setToolTipText("");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        panelSidebar.add(panelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 250, 70));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        panelViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelViewAllRecordMouseExited(evt);
            }
        });
        panelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnViewAllRecord.setText("View All Record");
        btnViewAllRecord.setToolTipText("");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });
        panelViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        panelSidebar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 250, 70));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText("  Log Out");
        btnLogout.setToolTipText("");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        panelLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        panelSidebar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 250, 70));

        getContentPane().add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        clearTable();
        switch (combo_lastday.getSelectedIndex()) {
            case 0:
                clearTable();
                sevenDays();
                break;
            case 1:
                clearTable();
                oneMonth();
                break;
            case 2:
                clearTable();
                sixMonth();
                break;
            case 3:
                clearTable();
                oneYear();
                break;
            case 4:
                clearTable();
                threeYear();
                break;
            case 5:
                clearTable();
                sixYear();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Invalid Selection");
                break;
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void combo_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_courseActionPerformed
        
    }//GEN-LAST:event_combo_courseActionPerformed

    private void combo_lastdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_lastdayActionPerformed
       
    }//GEN-LAST:event_combo_lastdayActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        Color clr=new Color(0,51,51);
        btnHome.setBackground(clr);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        Color clr=new Color(0,102,102);
        btnHome.setBackground(clr);
    }//GEN-LAST:event_lblHomeMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr=new Color(0,51,51);
        btnHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited

    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        search_record_page search = new search_record_page();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        Color clr=new Color(0,51,51);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        Color clr=new Color(0,102,102);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void panelSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchRecordMouseClicked
        search_record_page search = new search_record_page();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelSearchRecordMouseClicked

    private void panelSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchRecordMouseEntered
        Color clr=new Color(0,51,51);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_panelSearchRecordMouseEntered

    private void panelSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchRecordMouseExited
        Color clr=new Color(0,102,102);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_panelSearchRecordMouseExited

    private void btnEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseClicked
        update_course_page updateCourse = new update_course_page();
        updateCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditCourseMouseClicked

    private void btnEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseEntered
        Color clr=new Color(0,51,51);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseEntered

    private void btnEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseExited
        Color clr=new Color(0,102,102);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseExited

    private void panelEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditCourseMouseClicked
        update_course_page updateCourse = new update_course_page();
        updateCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelEditCourseMouseClicked

    private void panelEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditCourseMouseEntered
        Color clr=new Color(0,51,51);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_panelEditCourseMouseEntered

    private void panelEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditCourseMouseExited
        Color clr=new Color(0,102,102);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_panelEditCourseMouseExited

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        View_Course_Page viewCourse = new View_Course_Page();
        viewCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseListMouseClicked

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        Color clr=new Color(0,51,51);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        Color clr=new Color(0,102,102);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void panelCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCourseListMouseClicked
        View_Course_Page viewCourse = new View_Course_Page();
        viewCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelCourseListMouseClicked

    private void panelCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCourseListMouseEntered
        Color clr=new Color(0,51,51);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_panelCourseListMouseEntered

    private void panelCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCourseListMouseExited
        Color clr=new Color(0,102,102);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_panelCourseListMouseExited

    private void btnViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseClicked
        View_All_Record_Page allRecord = new View_All_Record_Page();
        allRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewAllRecordMouseClicked

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        Color clr=new Color(0,51,51);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        Color clr=new Color(0,102,102);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void panelViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordMouseClicked
        View_All_Record_Page allRecord = new View_All_Record_Page();
        allRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelViewAllRecordMouseClicked

    private void panelViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordMouseEntered
        Color clr=new Color(0,51,51);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_panelViewAllRecordMouseEntered

    private void panelViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordMouseExited
        Color clr=new Color(0,102,102);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_panelViewAllRecordMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        Login_Page login = new Login_Page();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Color clr=new Color(0,51,51);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        Color clr=new Color(0,102,102);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void panelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseClicked
        Login_Page login = new Login_Page();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelLogoutMouseClicked

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered

    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited

    }//GEN-LAST:event_panelLogoutMouseExited
    public void sevenDays()
    {
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        cal.add(Calendar.DATE, -7);
        String then = sdf.format(cal.getTime());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cd = dtf.format(now);
        
        
        
        
        String cname = combo_course.getSelectedItem().toString();
        Float totalAmount = 0.0f;
        
        try {
            DefaultTableModel model;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select * from fees_details where date between ? and ? and courses = ? ");
            pst.setString(1, then);
            pst.setString(2,  cd);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next())
            {
                String recieptNo = rs.getString("recepit_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                String paymentMode = rs.getString("payment_mode");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
            
                Object[] obj = {recieptNo,rollNo,studentName,courseName,amount,paymentMode,date,remark};
                model = (DefaultTableModel)tbl_viewrecord.getModel();
                model.addRow(obj);
                
                
                totalAmount = totalAmount + amount;
            }    
                lbl_amount_collected.setText(totalAmount.toString());
                lbl_selectcourse.setText(cname);
                lbl_words.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void oneMonth()
    {
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        cal.add(Calendar.MONTH, -1);
        String then = sdf.format(cal.getTime());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cd = dtf.format(now);
        
        
        
        
        String cname = combo_course.getSelectedItem().toString();
        Float totalAmount = 0.0f;
        
        try {
            DefaultTableModel model;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select * from fees_details where date between ? and ? and courses = ? ");
            pst.setString(1, then);
            pst.setString(2,  cd);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next())
            {
                String recieptNo = rs.getString("recepit_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                String paymentMode = rs.getString("payment_mode");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
            
                Object[] obj = {recieptNo,rollNo,studentName,courseName,amount,paymentMode,date,remark};
                model = (DefaultTableModel)tbl_viewrecord.getModel();
                model.addRow(obj);
                
                
                totalAmount = totalAmount + amount;
            }    
                lbl_amount_collected.setText(totalAmount.toString());
                lbl_selectcourse.setText(cname);
                lbl_words.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void sixMonth()
    {
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        cal.add(Calendar.MONTH, -6);
        String then = sdf.format(cal.getTime());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cd = dtf.format(now);
        
        
        
        
        String cname = combo_course.getSelectedItem().toString();
        Float totalAmount = 0.0f;
        
        try {
            DefaultTableModel model;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select * from fees_details where date between ? and ? and courses = ? ");
            pst.setString(1, then);
            pst.setString(2,  cd);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next())
            {
                String recieptNo = rs.getString("recepit_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                String paymentMode = rs.getString("payment_mode");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
            
                Object[] obj = {recieptNo,rollNo,studentName,courseName,amount,paymentMode,date,remark};
                model = (DefaultTableModel)tbl_viewrecord.getModel();
                model.addRow(obj);
                
                
                totalAmount = totalAmount + amount;
            }    
                lbl_amount_collected.setText(totalAmount.toString());
                lbl_selectcourse.setText(cname);
                lbl_words.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void oneYear()
    {
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        cal.add(Calendar.YEAR, -1);
        String then = sdf.format(cal.getTime());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cd = dtf.format(now);
        
        
        
        
        String cname = combo_course.getSelectedItem().toString();
        Float totalAmount = 0.0f;
        
        try {
            DefaultTableModel model;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select * from fees_details where date between ? and ? and courses = ? ");
            pst.setString(1, then);
            pst.setString(2,  cd);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next())
            {
                String recieptNo = rs.getString("recepit_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                String paymentMode = rs.getString("payment_mode");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
            
                Object[] obj = {recieptNo,rollNo,studentName,courseName,amount,paymentMode,date,remark};
                model = (DefaultTableModel)tbl_viewrecord.getModel();
                model.addRow(obj);
                
                
                totalAmount = totalAmount + amount;
            }    
                lbl_amount_collected.setText(totalAmount.toString());
                lbl_selectcourse.setText(cname);
                lbl_words.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void threeYear()
    {
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        cal.add(Calendar.YEAR, -3);
        String then = sdf.format(cal.getTime());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cd = dtf.format(now);
        
        
        
        
        String cname = combo_course.getSelectedItem().toString();
        Float totalAmount = 0.0f;
        
        try {
            DefaultTableModel model;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select * from fees_details where date between ? and ? and courses = ? ");
            pst.setString(1, then);
            pst.setString(2,  cd);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next())
            {
                String recieptNo = rs.getString("recepit_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                String paymentMode = rs.getString("payment_mode");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
            
                Object[] obj = {recieptNo,rollNo,studentName,courseName,amount,paymentMode,date,remark};
                model = (DefaultTableModel)tbl_viewrecord.getModel();
                model.addRow(obj);
                
                
                totalAmount = totalAmount + amount;
            }    
                lbl_amount_collected.setText(totalAmount.toString());
                lbl_selectcourse.setText(cname);
                lbl_words.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void sixYear()
    {
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        cal.add(Calendar.YEAR, -6);
        String then = sdf.format(cal.getTime());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String cd = dtf.format(now);
        
        
        
        
        String cname = combo_course.getSelectedItem().toString();
        Float totalAmount = 0.0f;
        
        try {
            DefaultTableModel model;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root","");
            PreparedStatement pst=Con.prepareStatement("select * from fees_details where date between ? and ? and courses = ? ");
            pst.setString(1, then);
            pst.setString(2,  cd);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next())
            {
                String recieptNo = rs.getString("recepit_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                String paymentMode = rs.getString("payment_mode");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
            
                Object[] obj = {recieptNo,rollNo,studentName,courseName,amount,paymentMode,date,remark};
                model = (DefaultTableModel)tbl_viewrecord.getModel();
                model.addRow(obj);
                
                
                totalAmount = totalAmount + amount;
            }    
                lbl_amount_collected.setText(totalAmount.toString());
                lbl_selectcourse.setText(cname);
                lbl_words.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void clearTable()
    {
        DefaultTableModel model = (DefaultTableModel) tbl_viewrecord.getModel();
        model.setRowCount(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEditCourse;
    private javax.swing.JPanel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> combo_course;
    private javax.swing.JComboBox<String> combo_lastday;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lbl_amount_collected;
    private javax.swing.JLabel lbl_selectcourse;
    private javax.swing.JLabel lbl_words;
    private javax.swing.JPanel panelCourseList;
    private javax.swing.JPanel panelEditCourse;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelSearchRecord;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JTable tbl_viewrecord;
    private javax.swing.JPanel txt_course;
    // End of variables declaration//GEN-END:variables

    
}
